AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Standalone Google OAuth Connector Service

Parameters:
  JwtSessionsTable:
    Type: String
    Default: toolgate-jwt-sessions
    Description: DynamoDB table for JWT allowlist

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.10
    Environment:
      Variables:
        LOG_LEVEL: INFO
        SESSIONS_TABLE_NAME: !Ref GoogleSessionsTable
        LAMBDA_URL: https://google.toolgate.dev

Resources:
  # DynamoDB Table for Google OAuth Sessions
  GoogleSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: toolgate-keychain-google-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Lambda Function with SAM Events
  GoogleConnectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: toolgate-keychain-google
      CodeUri: src/
      Handler: app.lambda_handler
      Layers:
        - arn:aws:lambda:us-east-1:253949037832:layer:toolgate-common:55
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: '{{resolve:secretsmanager:toolgate/google-oauth:SecretString:client_id}}'
          GOOGLE_CLIENT_SECRET: '{{resolve:secretsmanager:toolgate/google-oauth:SecretString:client_secret}}'
          SESSIONS_TABLE: !Ref JwtSessionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GoogleSessionsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:toolgate/google-oauth*
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${JwtSessionsTable}
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"
      Events:
        # Public routes (no auth - OAuth flow)
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE
        Info:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /info
            Method: GET
            Auth:
              Authorizer: NONE
        Connect:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /connect
            Method: POST
            Auth:
              Authorizer: NONE
        OAuthCallback:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /oauth/callback
            Method: GET
            Auth:
              Authorizer: NONE
        SessionPoll:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /session/{sessionId}
            Method: GET
            Auth:
              Authorizer: NONE
        # Protected routes (require JWT)
        Credentials:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /credentials
            Method: GET
        Disconnect:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /disconnect
            Method: POST

  # HTTP API with Shared Authorizer
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Auth:
        DefaultAuthorizer: SharedAuthorizer
        Authorizers:
          SharedAuthorizer:
            FunctionArn: !ImportValue toolgate-shared-authorizer-arn
            AuthorizerPayloadFormatVersion: "2.0"
            EnableSimpleResponses: false
            Identity:
              Headers:
                - Authorization
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # Custom Domain
  CustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: google.toolgate.dev
      DomainNameConfigurations:
        - CertificateArn: arn:aws:acm:us-east-1:253949037832:certificate/fc380532-1035-45a1-8c81-eaeec80b7e42
          EndpointType: REGIONAL

  # API Mapping
  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref CustomDomain
      ApiId: !Ref HttpApi
      Stage: $default

  # Route53 Record
  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z025643316R5XH8VTEVHY
      Name: google.toolgate.dev
      Type: A
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId

Outputs:
  CustomDomainUrl:
    Description: Custom Domain URL
    Value: https://google.toolgate.dev
  
  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  
  FunctionName:
    Description: Google Connector Function Name
    Value: !Ref GoogleConnectorFunction
  
  SessionsTableName:
    Description: Google Sessions DynamoDB Table
    Value: !Ref GoogleSessionsTable
