AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Standalone Google OAuth Connector Service

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.10
    Environment:
      Variables:
        LOG_LEVEL: INFO
        SESSIONS_TABLE_NAME: !Ref SessionsTable
        LAMBDA_URL: https://google.toolgate.dev

Resources:
  # DynamoDB Table for Sessions
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: toolgate-google-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Lambda Function
  GoogleConnectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: toolgate-google-connector
      CodeUri: src/
      Handler: app.lambda_handler
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: '{{resolve:secretsmanager:toolgate/google-oauth:SecretString:client_id}}'
          GOOGLE_CLIENT_SECRET: '{{resolve:secretsmanager:toolgate/google-oauth:SecretString:client_secret}}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:toolgate/google-oauth*
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"

  # HTTP API
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # Lambda Integration
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GoogleConnectorFunction.Arn
      PayloadFormatVersion: '2.0'

  # Catch-all route
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: $default
      Target: !Sub integrations/${LambdaIntegration}

  # Lambda permission for API Gateway
  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GoogleConnectorFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*

  # Custom Domain
  CustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: google.toolgate.dev
      DomainNameConfigurations:
        - CertificateArn: arn:aws:acm:us-east-1:253949037832:certificate/fc380532-1035-45a1-8c81-eaeec80b7e42
          EndpointType: REGIONAL

  # API Mapping
  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref CustomDomain
      ApiId: !Ref HttpApi
      Stage: $default

  # Route53 Record
  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z025643316R5XH8VTEVHY
      Name: google.toolgate.dev
      Type: A
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId

Outputs:
  CustomDomainUrl:
    Description: Custom Domain URL
    Value: https://google.toolgate.dev
  
  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  
  FunctionName:
    Description: Google Connector Function Name
    Value: !Ref GoogleConnectorFunction
  
  SessionsTableName:
    Description: Google Sessions DynamoDB Table
    Value: !Ref SessionsTable
